### ISSUE TITLE
ImageSharp

### ISSUE THREAD

**Issue by elijahr2411** [MarcusWichelmann/MarcusW.VncClient#16]
Hi! Do you have any pointers on getting your library to work with ImageSharp? I've read through the documentation and am honestly quite confused, it'd be great if you could help a bit. My goal is to, on each frame update, render the frame into an ImageSharp image for use with my program. Thanks!

**Comment by MarcusWichelmann** [comment]
Hi, interesting idea.
You could do that by implementing your own `IRenderTarget`. For that, please see the [Readme](https://github.com/MarcusWichelmann/MarcusW.VncClient#manual-integration) and this Avalonia-specific sample implementation:
https://github.com/MarcusWichelmann/MarcusW.VncClient/blob/master/src/MarcusW.VncClient.Avalonia/RfbRenderTarget.cs#L31

You would only have to implement the `GrabFramebufferReference` method. As you can see, there it creates a `WriteableBitmap`, which is also Avalonia-specific, but could be any other Bitmap implementation. All the VNC-Client implementation needs, is a pointer to the memory, where *whatever* Bitmap implementation stores its image.

So after looking at the [ImageSharp documentation](https://docs.sixlabors.com/articles/imagesharp/pixelbuffers.html), your best bet would probably be, to allocate your own `byte[] rgbaBytes` with the required size for all the pixels, return a `IFramebufferReference` with a pointer to that byte-array and then use the Dispose method of your `IFramebufferReference? implementation (see [here](https://github.com/MarcusWichelmann/MarcusW.VncClient/blob/9d9fbf7b97b390ca9f0dff68ba52d2b9a85aed09/src/MarcusW.VncClient.Avalonia/Adapters/Rendering/AvaloniaFramebufferReference.cs)) to pass the byte-array to ImageSharp using a callback when the rendering is finished:
```c#
using (var image = Image.LoadPixelData<Rgba32>(rgbaBytes, width, height))
{
    // Work with the image
}
```

Hope that helps.
