### ISSUE TITLE
有一些问题需要请教

### ISSUE THREAD

**Issue by ldcx9** [MarcusWichelmann/MarcusW.VncClient#19]
我使用net5 webapi想接入完成一套本地的网站，让用户打开之后可以在网页上展示所有连接的VNC设备的实时画面并操作，想请教一下有什么办法或思路可以实现嘛

I use the net5 webapi to access and complete a set of local websites, so that users can display the real-time images of all connected VNC devices and operate them on the website after opening. I want to ask what methods or ideas can be achieved

**Comment by ldcx9** [comment]
Please give me some of your contact information, such as Telegram

**Comment by MarcusWichelmann** [comment]
I don't provide personal support via Telegram, but maybe https://github.com/MarcusWichelmann/MarcusW.VncClient/discussions/15 or https://github.com/MarcusWichelmann/MarcusW.VncClient/discussions/10 can be helpful.
