### ISSUE TITLE
Does not work with beta: Avalonia 0.10.0-rc1

### ISSUE THREAD

**Issue by fapo85** [MarcusWichelmann/MarcusW.VncClient#4]
There is a problem with logging, so it does not work with the current beta.
However, many projects already require this version.

**Comment by MarcusWichelmann** [comment]
@fapo85 Thanks for your report, this is a known issue. Avalonia introduces some breaking API changes with the upcoming release. I think I'll fix the compatibility issues in a seperate branch that will be merged as soon as Avalonia 0.10 is released.

**Comment by MarcusWichelmann** [comment]
@fapo85 I've published a release now, which should work with Avalonia 0.10.0: https://www.nuget.org/packages/MarcusW.VncClient/1.0.0-alpha4
