### ISSUE TITLE
Screenshot saved as img?

### ISSUE THREAD

**Issue by Ovi-bear** [MarcusWichelmann/MarcusW.VncClient#9]
how I capture screenshot and save it as image?

**Comment by MarcusWichelmann** [comment]
You could implement a custom render target that takes the received framebuffers and writes each frame as JPEG/PNG to the disk. If you need only one frame, you could close the connection right after that.
Please check out https://github.com/MarcusWichelmann/MarcusW.VncClient#manual-integration and https://github.com/MarcusWichelmann/MarcusW.VncClient/blob/master/src/MarcusW.VncClient.Avalonia/RfbRenderTarget.cs.

This approach should even work in console applications, no UI framework required.
